name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/commitlint.yml"
      - ".github/workflows/release-pr.yml"
      - ".husky/"
      - "commitlint.config.cjs"
  workflow_dispatch:
    branches:
      - master

jobs:
  cache-pnpm:
    name: Cache Pnpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile, --prefer-offline]
  release:
    needs: cache-pnpm
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: |
            - args: [--frozen-lockfile, --prefer-offline]
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Commit files
        run: |
          rm -f ./.gitignore
          cp ./release.gitignore ./.gitignore
          git rm --cached "*"
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Release" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: "refs/heads/release"
